server:
  port: 8081


  #DB--mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wetebot?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8&serverTimezone=GMT
    username: chauncey
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: quartzScheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true




#imade save path
img:
  root-path: ./images/
  qr-path: ./images/qrpath

#job path
job:
  root-package: "com.chauncey.WeTeBot.job."


# api
api:
  # auto chat
  chat:
    url: 'https://api.ai.qq.com/fcgi-bin/nlp/nlp_textchat'
    app_id: 
    app_key: 
  #weather
  weather:
    key: 
    url: 'https://free-api.heweather.net/s6/weather/%s?location=%s&key=%s'
    type:
      now: now
      forecast: forecast
      lifestyle: lifestyle
